apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-goof
  namespace: java-goof
  labels:
    app: java-goof
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-goof
  template:
    metadata:
      labels:
        app: java-goof
    spec:
      containers:
      - name: java-goof
        image: 199694721883.dkr.ecr.us-west-2.amazonaws.com/cs-reinvent-demo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-goof-service
  namespace: java-goof
spec:
  selector:
    app: java-goof
  type: LoadBalancer  
  ports:
  - port: 8080
    targetPort: 8080