name: java-goof image build and deployment

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'    

permissions:
 id-token: write
 contents: read # This is required for actions/checkout@v2

jobs:
  build-todolist-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todolist-goof
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          load: true
          context: todolist-goof
          push: false
          tags: java-goof:latest

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.24.0'
        id: install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-session-name: JavaGoofDeployment
          aws-region: us-west-2        

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
    
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: cs-reinvent-demo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          DOCKER_BUILDKIT=1 docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY  

      - name: Trend Cloud One Container Security Scan Action
        run: |
          export CLOUD_ONE_API_KEY=${{ secrets.TMAS_API_KEY }}
          echo $ECR_REGISTRY
          echo $ECR_REPOSITORY
          curl -s -L https://gist.github.com/raphabot/abae09b46c29afc7c3b918b7b8ec2a5c/raw/ | bash
          tmas scan registry:$ECR_REGISTRY/$ECR_REPOSITORY

      - name: Update kube config
        run: aws eks update-kubeconfig --name adorable-creature-1669314578 --region us-west-2  

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/java-goof.yaml
