name: java-goof image build and deployment

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'    

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build-todolist-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todolist-goof
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          load: true
          context: todolist-goof
          push: false
          tags: java-goof:latest

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.24.0'
        id: install

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-central-1-docker.pkg.dev
          gcloud build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/java-goof/java-goof:latest .
          docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/java-goof/java-goof:latest

      - name: Trend Cloud One Container Security Scan Action 
        run: |
         export CLOUD_ONE_API_KEY=${{ secrets.TMAS_API_KEY }}
         curl -s -L https://gist.github.com/raphabot/abae09b46c29afc7c3b918b7b8ec2a5c/raw/ | bash
         tmas scan registry:us-central1-docker.pkg.dev/$GOOGLE_PROJECT/java-goof/java-goof:latest

#      - name: Deploy to GKE
#        env:
#          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
#        run: |
#          gcloud container clusters get-credentials igorsdevcluster --region us-central1
#          sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" k8s/java-goof.yaml
#          kubectl apply -f k8s/java-goof.yaml
